name: "Exemplo pipeline"

on:
  workflow_dispatch:
  push: [main]

jobs:
  integracao-continua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Listagem de conteúdos do diretório
        run: ls -la
      - name: Outro echo
        run: echo "Qualquer coisa"
  estagio02:
    needs: estagio01
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: sleep 5
  estagio03:
    needs: estagio02
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: sleep 2