name: "Exemplo pipeline"

on:
  workflow_dispatch:
  push: 
    branches: [main]

jobs:
  integracao-continua:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: aplicacao.app:APP
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instalação de dependências
        run: pip install -r requirements.txt
      # - name: Migração
      #   run: |
      #     flask db init
      #     flask db migrate -m "First"
      #     flask db upgrade
      - name: Testes unitários
        run: pytest aplicacao/
  entrega-continua:
    needs: integracao-continua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v4
      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build e push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tag: ${{ vars.DOCKER_USERNAME }}/mateus-irineu-guimaraes-mallmann:27-06-26